version: '3'
services:
  nginx:
    image: 807775553447.dkr.ecr.us-east-2.amazonaws.com/gitactions:${{ github.sha }}
    ports:
      - "80:80"
    restart: always
    container_name: my-nginx-container